[Registration] add a step for organization selection in registration form
claroline/Claroline pull request #1728
Opened 2021-06-11 17:39 UTC by YanaMIvanova

| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No

The following pull request adds a step for an organization choice in the registration form.

This makes it possible for a user to select the organization they belong to. This behaviour is controlled by a flag that is used to enable/disable the feature - `allow_organization_selection` (defaults to `false`)

If a chosen organization contains other organizations within it, another dropdown is shown for a further selection. 

On each selection, the organization in question is set in the Store as a `mainOrganization`, regardless of it being a parent or a child.

![image](https://user-images.githubusercontent.com/26501599/121726240-f5d1dd00-caf2-11eb-9dd7-ec81453e79f2.png)

2021-06-11 17:45 UTC, maieutiquer commented
Note: testing is awkward because of https://github.com/claroline/Claroline/issues/1727

2021-06-15 07:04 UTC, Elorfin requested changes
IMHO, we should also disallow to use both options `forceOrganizationCreation` and `allowOrganizationSelection` at the same time. 

Both are used to fill the `mainOrganization` of the user and one will override the other.

2021-06-15 07:04 UTC, Elorfin commented on src/main/core/Controller/APINew/User/RegistrationController.php
> +                'allowOrganizationSelection' => $this->config->getParameter('registration.allow_organization_selection'),
Can you expose the new option in the ui parameters please ? https://github.com/claroline/Claroline/blob/13.x/src/main/core/Resources/modules/administration/community/parameters/components/parameters-tab.jsx#L56

2021-06-15 07:04 UTC, Elorfin commented on src/main/app/Resources/modules/security/registration/components/main.jsx
> +        title: trans('organizations_selector'),
You can just reuse `trans('organization')`.

2021-06-15 13:35 UTC, YanaMIvanova commented on src/main/app/Resources/modules/security/registration/components/organizationSelection.jsx
> +      <>
Yes, it is the same. I changed it to `Fragment` for consistency

2021-06-15 15:53 UTC, YanaMIvanova commented
> IMHO, we should also disallow to use both options `forceOrganizationCreation` and `allowOrganizationSelection` at the same time.
> 
> Both are used to fill the `mainOrganization` of the user and one will override the other.

Both options could be presented as radio buttons.
Would this be a proper behaviour? 

![image](https://user-images.githubusercontent.com/26501599/122085023-0217ac00-ce0b-11eb-8cfb-d7cbae18fd2b.png)

2021-06-17 08:45 UTC, YanaMIvanova commented on src/main/app/Resources/modules/security/registration/components/organizationSelection.jsx
> +    </form>
`FormData` component seems to use the store for reading and writing (two-way data binding). As a result, every input in it shares the same content (the data in `mainOrganization.code`) 

![image](https://user-images.githubusercontent.com/26501599/122362942-369d7c00-cf61-11eb-8578-f7c5ca0bd4dc.png)

2021-06-17 11:18 UTC, Elorfin commented on src/main/app/Resources/modules/security/registration/components/organizationSelection.jsx
> +    </form>
In fact you can use fields for props which does not belong to the form model (we usually add `_` as prefix for this). You can then add an `onChange(newValue)` on the input to update the final `mainOrganization` prop (which will be saved).

Here is an example of this kind of advanced configuration in forms : https://github.com/claroline/Claroline/blob/13.x/src/plugin/agenda/Resources/modules/events/event/components/form.jsx#L65.

2021-06-17 11:23 UTC, Elorfin commented
> Both options could be presented as radio buttons.

This is a good idea. Both options should also be merged into one to simplify things. For example `organizationSelection: 'none'|'create'|'select'`.

We'll need an updater to set the new option for existing platforms. If you don't know how to do an Updater, let me know, I can do it for you.

2021-06-21 13:26 UTC, YanaMIvanova commented on src/main/app/Resources/modules/security/registration/components/organizationSelection.jsx
> +    </form>
Thanks, I updated and pushed the form - now each input field has its own value

2021-06-24 13:49 UTC, YanaMIvanova commented
I moved all organization options (`'none'|'create'|'select'`) into one prop

> We'll need an updater to set the new option for existing platforms. If you don't know how to do an Updater, let me know, I can do it for you.

Thanks, that would be really helpful

2021-06-25 08:38 UTC, Elorfin commented on .gitignore
> +.idea
Should not have been commited. You should ignore it through your global `.gitignore`.

2021-06-25 08:39 UTC, Elorfin commented on src/main/app/Resources/modules/security/registration/constants.js
> +  [ORGANIZATION_SELECTION_NONE]: 'No selection',
Missing translation

2021-06-28 06:41 UTC, Elorfin approved these changes
👍

2021-06-28 06:41 UTC, merged