Quotas management
claroline/Claroline pull request #1790
Opened 2021-08-13 16:10 UTC by firepolo

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | yes
| Fixed issues | comma-separated list of issues fixed by the PR, if any

# Description
Add a feature for add quota managment in Claroline, we can activate or not the option.

# Screenshots
Add tool in training menu
![image](https://user-images.githubusercontent.com/1777148/129387115-c1d3770b-5012-4fe5-a88c-2307ee522c65.png)

Add options in session parameters
![image](https://user-images.githubusercontent.com/1777148/129387035-39cdab65-ce00-4a43-bfa1-eb79ceb953ff.png)

Add view for list & edit quotas
![image](https://user-images.githubusercontent.com/1777148/129387414-e73fc8b3-b51b-47fb-b91c-e079eb7342f1.png)

Add view for list & manage subscriptions
![image](https://user-images.githubusercontent.com/1777148/129387555-dc5fcba6-8e13-4c43-9945-cfc7859e18f6.png)
![image](https://user-images.githubusercontent.com/1777148/129387687-d7c6cc7f-dd0e-4b1f-81b4-7e20380f67fc.png)

2021-08-18 08:15 UTC, Elorfin requested changes
I still need to test it and check why status management is so complex.

2021-08-18 08:15 UTC, Elorfin commented on src/plugin/cursus/Resources/modules/tools/trainings/quota/store/actions.js
> +      url: url(['apiv2_cursus_quota_find'], {filters: {uuid: id}}),
use `get` endpoint instead.

2021-08-18 08:15 UTC, Elorfin commented on src/plugin/cursus/Resources/modules/tools/trainings/quota/store/actions.js
> +        url: ['apiv2_cursus_quota_open', {id}],
use `get` endpoint instead.

2021-08-18 08:15 UTC, Elorfin commented on src/plugin/cursus/Resources/modules/tools/trainings/subscription/components/page.jsx
> +    <PageFull
Same comment than for Quota

2021-08-18 08:15 UTC, Elorfin commented on src/plugin/cursus/Resources/modules/tools/trainings/subscription/containers/main.jsx
> +import {selectors, actions, reducer} from '#/plugin/cursus/tools/trainings/quota/store'
You shouldn't request a part of another sub app.

2021-08-29 21:42 UTC, firepolo commented on src/main/core/Resources/modules/data/types/organization/components/input.jsx
> +    label={trans('set_organization')}
I fix

2021-08-29 21:42 UTC, firepolo commented on src/main/core/API/Serializer/Platform/ClientSerializer.php
> +            'quotas' => $this->config->getParameter('quotas'),
I remove the line

2021-08-29 21:49 UTC, firepolo commented on src/plugin/cursus/Controller/QuotaController.php
> +    public function listAction(Request $request, $class = Quota::class): JsonResponse
I remove this function

2021-08-29 21:52 UTC, firepolo commented on src/plugin/cursus/Entity/Session.php
> +    private $usedByQuotas = false;
Yes, I you agree. I have no time for this refactor now. But I can do this later.

2021-08-29 21:54 UTC, firepolo commented on src/plugin/cursus/Repository/SessionUserRepository.php
> +    public function findByQuota(Quota $quota)
I renamed this

2021-08-29 22:03 UTC, firepolo commented on src/plugin/cursus/Resources/modules/quota/components/list.jsx
> +        type: 'string',
It's done, but I have error with the property at "primary: true". Can I keep it primary and have the primaryAction ?

2022-02-09 07:25 UTC, Elorfin commented
This contains to many changes to be merge.
If you want to add it to the code base, you'll need to break it in multiple PRs.

Also note ;
- We will not accept new dependencies. All the export of Claroline are done in CSV which is natively supported by MSExcel,
- No extensions for Doctrine.
- No new endpoints in the core API.

2022-02-09 07:25 UTC, closed without merging

2022-02-11 12:21 UTC, maieutiquer commented
Temporarily restoring the branch in order to check if we have everything on our side as well