Custom color Chart
claroline/Claroline pull request #2477
Opened 2023-05-12 06:43 UTC by WolfyWin

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Fixed issues | comma-separated list of issues fixed by the PR, if any

2023-05-12 19:16 UTC, WolfyWin commented
Je n'ai pas trouvé d'autres façon d'ajouter les palettes dans le formulaire ( à part créer un nouveau type pour formData) donc j'ai laissé tel quel pour le moment. De ce fait le nombre de couleurs das la palette est limitée au nombre de champs présent dans le formulaire (actuellement 4).

2023-05-15 06:28 UTC, Elorfin requested changes
Pour ce qui est de l'ajout / modification des couleurs, ce n'est en effet pas possible de le gérer directement à l'aide du `FormData`.

Il faut que tu créés tes propres composants pour le faire (avant le bouton ici https://github.com/claroline/Claroline/pull/2477/files#diff-51fa040cb21f415bd76204fcde716dba4a2ce067e654c0e868a057ab3cdbc7dcR48).

Tu as un sélecteur dans le form qui permet de récupérer les data courantes de ton formulaire.
Tu as également une action `updateProp` qui te permet de mettre à jour les data du formulaire.

2023-05-15 06:28 UTC, Elorfin commented on src/main/core/Resources/styles/administration/parameters.less
> +.color-pastille {
C'est mieux de conserver le même préfixes : `.color-chart-colors` et `.color-chart-color`.

2023-05-15 06:28 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/components/colorCharts.jsx
> +    <div>
Peut être remplacé par un `Fragment` react.

2023-05-15 06:28 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/components/colorCharts.jsx
> +              style={{marginLeft: 'auto'}}
A mettre dans le CSS.
On évite les styles en dur dans le JS.

2023-05-15 06:28 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/components/colorCharts.jsx
> +            </div>
Cette div est inutile imo.

2023-05-15 06:28 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/components/colorCharts.jsx
> +            </div>
Tu peux peut-être aussi utilisé le composant `ContentTitle`.
Il est capable de gérer ta toolbar grâce à la prop `actions`.

2023-05-15 06:28 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/components/tool.jsx
> +  availableColorCharts: T.array.isRequired,
Tu ne t'en sers pas. Pas besoin de le déclarer.

2023-05-15 06:28 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/containers/tool.jsx
> +    availableColorCharts: selectors.availableColorCharts(state)
Tu ne l'utilises pas, à supprimer.

2023-05-15 06:28 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/modals/color-chart-edit/components/modal.jsx
> +}
Tu n'aurais qu'une seule modale `ColorChartParameters` qui va gérer la création et la mise à jour.
Pas besoin de créer 2 chaînes de composants complètes alors qu'on ne va que changer le endpoint de l'api qu'on utilise lors de la sauvegarge.

FYI : il y a un sélecteur dans le form qui permet de savoir si on est en train de créer ou de mettre à jour (isNew).

2023-05-15 06:28 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/modals/color-chart-edit/containers/modal.jsx
> +        }
tu as une méthode lodash pour cloner en profondeur un objet : `import cloneDeep from 'lodash/cloneDeep'`.

2023-05-15 06:28 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/modals/color-chart-edit/store/actions.js
> +      url: ['apiv2_color_collection_update', {id: data.id}],
la création et la mise à jour ne peuvent pas passer par le même endpoint.
La création devrait utiliser `POST apiv2_color_collection_create`

2023-05-15 06:28 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/modals/color-chart-edit/store/actions.js
> +      },
les headers sont setté automatiquement par le noyau. A supprimer.

2023-05-15 06:28 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/modals/color-chart-edit/store/actions.js
> +      url: ['apiv2_color_collection_update', {id: data.id}],
il faut réutiliser l'action `save` du formulaire, elle fera le submit et le gestion des erreurs pour toi.

2023-05-15 06:28 UTC, Elorfin commented on src/main/theme/Serializer/ColorCollectionSerializer.php
> +            $this->sipe('colors', 'setColors', $data, $colorCollection);
pas besoin du if, le sipe le fait pour toi.

2023-05-15 06:28 UTC, Elorfin commented on src/main/theme/Subscriber/Administration/ParametersSubscriber.php
> +        $colorCharts = $this->objectManager->getRepository('Claroline\ThemeBundle\Entity\ColorCollection')->findAll();
il vaut mieux utiliser la vrai classe `use Claroline\ThemeBundle\Entity\ColorCollection;` et `getRepository(ColorCollection::class)`

2023-05-15 07:47 UTC, WolfyWin commented on src/main/theme/Resources/modules/administration/appearance/containers/tool.jsx
> +    availableColorCharts: selectors.availableColorCharts(state)
Si, ça permet de load instantanément la palette sauvegarder sans avoir à refresh la page.

2023-05-15 08:46 UTC, WolfyWin commented on src/main/theme/Resources/modules/administration/appearance/components/colorCharts.jsx
> +            </div>
J'ai essayé d'utiliser le ContentTitle mais je ne peux plus afficher correctement le css

2023-05-15 08:48 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/components/colorCharts.jsx
> +            </div>
ça permet justement d'enlever une partie du css custom que tu as fait.
N'y touche pas pour le moment, on regardera ensemble quand tu auras fait le reste.

2023-05-15 18:11 UTC, WolfyWin commented
Ajout de gestion des couleurs de la palette :

![Capture d’écran du 2023-05-15 20-00-34](https://github.com/claroline/Claroline/assets/58392030/db462418-914a-4b63-930c-0fa487590650)
![Capture d’écran du 2023-05-15 20-00-29](https://github.com/claroline/Claroline/assets/58392030/50b49811-19e6-463e-a177-53632cb705d8)

2023-05-25 18:59 UTC, WolfyWin commented
- [x] Supression du début de cablage des colors dans data color input .
- [x] Supression du niveau view dans color.
- [x] Déclaration du store pour colorchart avec withreducer qui  se connecte pour récupérer les palettes.
- [x] Requête ajax à l'ouverture du picker pour récupérer la liste des palettes
- [x] Modification de l'ui de library avec la dropdown et la palettes disponible.
- [x] Blockage de la vue selecteur dans l'ajout et modification des palettes/couleurs.

![Capture d’écran du 2023-05-25 18-47-00](https://github.com/claroline/Claroline/assets/58392030/721d8754-59fc-4140-a129-ba32a6d79c5a)
![Capture d’écran du 2023-05-25 18-48-33](https://github.com/claroline/Claroline/assets/58392030/c456f43d-b32d-4367-a9f1-a8388758eb61)

2023-05-26 05:03 UTC, Elorfin commented on src/main/theme/Resources/modules/color/components/color-chart.jsx
> +      colorCharts: undefined
- Pas besoin de stocker tes color charts dans le state react. Tu peux les récupérer directement depuis le store redux. Idem dans ColorChartLibrary
- Pareil pour `viewLocked`, à récupérer direct depuis les props (tu peux faire le `this.props.viewLocked || this.props.colorChart.data.length === 0` qui se trouve plus loin directement dans le `render`, ce n'est pas une opération couteuse, on n'a pas besoin de stocker le résultat)

2023-05-26 05:04 UTC, Elorfin commented on src/main/theme/Resources/modules/color/components/library.jsx
> +class ColorChartLibrary extends Component {
Tu n'as pas besoin d'une classe component ici, il faut remettre un composant fonction.

2023-05-26 05:06 UTC, Elorfin commented on src/main/theme/Resources/modules/color/components/color-chart.jsx
> +    await this.props.load()
Optimization : si `viewLocked === true` alors pas besoin de charger les palettes puisqu'on n'y accèdera jamais.

2023-05-26 05:07 UTC, Elorfin commented on src/main/theme/Resources/modules/color/store/reducer.js
> +export const reducer = makeReducer({}, {
Tu vas recevoir un tableau de colorCharts ici, la valeur par défaut devrait donc aussi être un tableau.

2023-05-26 05:16 UTC, Elorfin commented
Le bouton delete devrait être positionné plus ou moins comme le violet ci-dessous :
![position](https://github.com/claroline/Claroline/assets/5363219/8dc45798-da2e-43fe-bae4-e910090bcfbb)

En contact avec la couleur qu'il est sensé supprimer.

2023-05-30 07:18 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/modals/color-chart-parameters/components/modal.jsx
> +          {...props}
- hideInput n'est pas utilisé, à supprimer.
- on ne déverse pas toutes les props aux children comme ça, il faut trier pour ne prendre que ce qu'on va utiliser.

2023-05-30 07:21 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/modals/color-chart-parameters/store/actions.js
> +}
il faut utiliser l'action de save fournie par le store du formulaire et supprimer cette action.

2023-05-30 07:22 UTC, Elorfin commented on src/main/theme/Resources/modules/color/components/color-chart.jsx
> +      noLibrary: true
pas besoin de stocker ça dans le state react. surtout que tu ne le lis jamais.

2023-05-31 04:48 UTC, Elorfin commented on src/main/theme/Resources/modules/administration/appearance/modals/color-chart-parameters/components/modal.jsx
> +        <span className="fa fa-fw fa-plus"></span>
- L'icone doit être settée via la prop `icon`.
- Il manque le label et une prop `tooltip="bottom"`

2023-05-31 05:01 UTC, Elorfin commented on src/main/theme/Resources/modules/color/components/color-chart.jsx
> +          noLibrary: this.props.noLibrary || !hasColorChart
Tu ne te sert plus de `this.state.noLibrary`.
A supprimer

2023-05-31 09:17 UTC, Elorfin approved these changes

2023-05-31 09:18 UTC, merged