moving privacy account core=> main->privacy
claroline/Claroline pull request #2489
Opened 2023-05-18 11:26 UTC by Noelle-M

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Fixed issues | comma-separated list of issues fixed by the PR, if any

2023-05-18 11:51 UTC, Noelle-M commented
J'avais supprimer le dossier privacy dans src/main/core/Resources/modules/account/privacy puisque plus raison d'être mais cela pose problème lors de la PR

2023-05-19 09:42 UTC, Elorfin requested changes

2023-05-19 09:42 UTC, Elorfin commented on src/main/core/Resources/modules/account/privacy/components/main.jsx
> +      title={trans('terms_of_service',{}, 'terms_of_service')}
le domaine devrait être privacy.

2023-05-19 09:42 UTC, Elorfin commented on src/main/privacy/Resources/modules/account/privacy/components/main.jsx
> +      title={trans('terms_of_service',{}, 'terms_of_service')}
le domaine devrait être privacy.

2023-05-19 09:42 UTC, Elorfin commented on src/main/privacy/Resources/modules/administration/privacy/components/tool.jsx
> +          title: trans('terms_of_service', {}, 'terms_of_service'),
le domaine devrait être privacy.

2023-05-19 09:42 UTC, Elorfin commented on src/main/privacy/Resources/modules/administration/privacy/components/tool.jsx
> +              label: trans('terms_of_service_activation_message', {}, 'terms_of_service'),
le domaine devrait être privacy.

2023-05-19 09:42 UTC, Elorfin commented on src/main/privacy/Resources/modules/administration/privacy/components/tool.jsx
> +              help: trans('terms_of_service_activation_help', {}, 'terms_of_service'),
le domaine devrait être privacy.

2023-05-19 09:42 UTC, Elorfin commented on src/main/privacy/Resources/modules/administration/privacy/components/tool.jsx
> +                  label: trans('terms_of_service', {}, 'terms_of_service'),
le domaine devrait être privacy.

2023-05-19 09:59 UTC, Noelle-M commented on src/main/core/Resources/modules/account/privacy/components/main.jsx
> +      title={trans('terms_of_service',{}, 'terms_of_service')}
c'est celui qui se situe dans le core, n'est-il pas voué à disparaître ?

2023-05-19 10:53 UTC, Elorfin approved these changes

2023-05-19 10:54 UTC, merged