Entity & Serializer
claroline/Claroline pull request #2531
Opened 2023-07-05 09:31 UTC by Noelle-M

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    |no
| Fixed issues | comma-separated list of issues fixed by the PR, if any

Nouvelle branche du plugin Privacy

2023-07-05 11:26 UTC, LaurentGruber requested changes

2023-07-05 11:26 UTC, LaurentGruber commented on src/main/privacy/Entity/PrivacyParameters.php
> +    use Template; // review avec Axel : relation vers template par defaut trait use template juste pour definition de la relation
inutile pour le moment.

2023-07-05 11:26 UTC, LaurentGruber commented on src/main/privacy/Controller/PrivacyController.php
> +    private TermsOfServiceManager $termsOfServiceManager;
non utilisé (et après aussi)

2023-07-05 11:26 UTC, LaurentGruber commented on src/main/privacy/Installation/ClarolinePrivacyInstaller.php
> +    public function getFixturesDirectory(): string
c'est inutile d'ajouter des fixtures

2023-07-05 11:26 UTC, LaurentGruber commented on src/main/privacy/Controller/PrivacyController.php
> +    private TermsOfServiceManager $termsOfServiceManager;
Il faut vérifier que tous les services que tu injectes, tu les utilises, sinon il faut les enlever.

2023-07-05 11:26 UTC, LaurentGruber commented on src/main/privacy/Controller/PrivacyController.php
> +    public function getName(): string
méthode inutile

2023-07-05 11:26 UTC, LaurentGruber commented on src/main/privacy/Controller/PrivacyController.php
> +    public function getClass(): string
méthode inutile

2023-07-05 12:40 UTC, LaurentGruber approved these changes

2023-07-05 16:09 UTC, LaurentGruber commented on src/main/privacy/Resources/config/services/updater.yml
> +      - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'
l'ordre n'est pas bon, il faut les inverser, si je ne m'abuse tu dois respecter l'ordre d'appel de tes services comme tu l'as mis dans le construct de ton updater

2023-07-06 10:04 UTC, LaurentGruber requested changes

2023-07-13 09:56 UTC, Elorfin requested changes

2023-07-13 09:56 UTC, Elorfin commented on src/main/privacy/Resources/modules/account/privacy/components/main.jsx
> +        target: route('accountPrivacy')
ça n'aurait pas du changer. la route `/accountPrivacy` n'existe pas

2023-07-13 09:56 UTC, Elorfin commented on src/main/privacy/Resources/modules/account/privacy/components/main.jsx
> +    data={props.fetch()}
- Pas de fetch dans le render react comme ça. see useEffect
- data n'est pas une prop de AccountPage

2023-07-13 09:56 UTC, Elorfin commented on src/main/privacy/Resources/modules/account/privacy/components/main.jsx
> -  privacy: T.shape({
Le composant attend toujours ces props.
Les propTypes n'auraient pas du être supprimée.

2023-07-13 09:56 UTC, Elorfin commented on src/main/privacy/Resources/modules/administration/privacy/store/selectors.js
> +const termsOfService = (state) => store(state).termsOfService
Il faut aussi utiliser reselect

2023-07-13 09:56 UTC, Elorfin commented on src/main/privacy/Controller/PrivacyController.php
> +        ]);
- Tu as un serializer pour ça (surtout que tu change le structure de données du DPO entre ce qui est resorti du serializer et ce qui sort de ce endpoint).

- Tu n'aurais pas du te limiter à la récupération du DPO. On veut aussi le pays de stockage de données dans la vue Account

Conclusion : tu n'aurais pas du toucher au endpoint que tu avais fait.

2023-07-24 06:32 UTC, Elorfin requested changes

2023-07-24 06:32 UTC, Elorfin commented on src/main/privacy/Controller/PrivacyController.php
> +        return new JsonResponse(['privacyParameters' => $data]);
Inutile de faire un sous objet. A restauter comme avant (penser à changer les usages dans l'ui)

2023-07-24 06:32 UTC, Elorfin commented on src/main/privacy/Resources/modules/account/privacy/containers/main.jsx
> +      privacyParameters: selectors.privacyParameters(state),
Comme pour l'admin, récupérer les infos individuellement (dpo, countryStorage...) depuis le store.

2023-12-21 07:31 UTC, closed without merging