[YouTube] use youtube video thumbnail as a resource thumbnail
claroline/Claroline pull request #2586
Opened 2023-09-07 09:31 UTC by WolfyWin

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no

2023-09-07 11:13 UTC, LaurentGruber commented
si c'est facile on pourra faire la même chose pour la ressource peertube ?

2023-09-08 10:14 UTC, Elorfin requested changes

2023-09-08 10:14 UTC, Elorfin commented on src/integration/youtube/Subscriber/Resource/VideoSubscriber.php
> +        }
Tu peux mettre toute la logique de création dans ton manager.
Les Listeners/Subscribers, c'est un peu comme les Controllers, ils gèrent l'orchestration. On évite de déclarer du code métier dedans.

2023-09-08 12:13 UTC, Elorfin approved these changes

2023-09-11 07:31 UTC, Elorfin approved these changes

2023-09-11 07:32 UTC, merged