[TAG] delete show tags
claroline/Claroline pull request #2610
Opened 2023-09-21 16:51 UTC by WolfyWin

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no

2023-09-25 06:04 UTC, Elorfin requested changes
On en discute en visio.

2023-09-25 06:04 UTC, Elorfin commented on src/main/core/API/Serializer/Resource/ResourceNodeSerializer.php
> +        }
Pourquoi ??
Je ne vois pas le rapport entre la date de création et la deserialization des tags?

2023-09-25 06:04 UTC, Elorfin commented on src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
> +        }
Pourquoi ??

2023-09-25 07:25 UTC, WolfyWin commented on src/main/core/API/Serializer/Workspace/WorkspaceSerializer.php
> +        }
C'est pour vérifier si il existe

2023-09-25 07:25 UTC, WolfyWin commented on src/main/core/API/Serializer/Resource/ResourceNodeSerializer.php
> +        }
C'est pour vérifier si il existe

2024-04-30 08:36 UTC, Elorfin commented
Directement intégré dans les refacto nécessaires pour la v15.

2024-04-30 08:36 UTC, closed without merging